### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by GregM1992** [nss-evening-cohort-24/gitsub-team-3#11]
Every page should have a profile rendered on the left side that looks the exact same each time.
------------------------------------------------------------------------------------------------------------
The user should see on the left hand of the screen a column containing information such as and ordered as:
------------------------------------------------------------------------------------------------------------------------
- a profile picture
- full name
- user name
- a short bio
- 3 buttons: a follow button, a sponsor button, and an options button
- a follower count 
- accounts followed
- favorite count
- *  indicates an icon needed along with information
-------------------------

- location *
- email address *
- landing page link*
- social media link*

---------------------------
- highlights header
- contributions*
- accolades*
- tags*

---------------------------

- organizations header
- small icons

-----------------------------

- sponsors header
- profile thumbnails with a continued button with number of remaining sponsors not shown

styling
-----------------------------

all text color should be white

--------------------------------

profile picture should be round with small border

-----------------------------------
buttons should be square with rounded edges

dependencies
------------------------------------------
#16 

dev notes
---------------------------------------------
this is tied to the data objects being created and needs those to properly render

![image](https://github.com/nss-evening-cohort-24/gitsub-team-3/assets/124316602/f1648628-f38e-4a29-b8a4-205e6f754d90)

**Comment by GregM1992** [comment]
updated issue

**Comment by keanacobarde** [comment]
Completed profile implementation and styling. Closing ticket.
