### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by GregM1992** [nss-evening-cohort-24/gitsub-team-3#12]
When scrolling to the bottom of the page the user should see a footer that has a span of hyperlinks such as : terms, privacy, security, status, etc. 

------------------------------------------------------------------------
As far as I understand these hyperlinks do not have to work.
----------------------------------------------------------------------

Acceptance criteria:
--------------------------------------------------------------------
at the bottom of every page there should be a footer

the letters for the "hyperlinks" should be blue

there should be a github logo between 10 "hyperlinks"

and a copyright tag on the left side

this tag should be a lighter color like very light grey or white

![image](https://github.com/nss-evening-cohort-24/gitsub-team-3/assets/124316602/ebf4a92d-5cfe-45aa-a786-7910c16e54ae)

**Comment by ndswimming92** [comment]
Will need to come back and try getting the font to change color. Opening another ticket.
