### ISSUE TITLE
CSS for each component

### ISSUE THREAD

**Issue by GregM1992** [nss-evening-cohort-24/gitsub-team-3#15]
# User Story
The user should see an accurately colored, organized, and styled GitHub clone that conforms to the requirements laid out in the WireFrame. The user should see a navbar, footer, and profile on each page with a content box that changes depending on the page. 

# Acceptance Criteria
WHEN the users launch, they should see the Overview page. The structure loosely follows: 
![image](https://github.com/nss-evening-cohort-24/gitsub-team-3/assets/97858910/2f52ea34-f0ef-4d3d-8b4b-77f728b999c9)
Measurements to be decided. Wireframe follows ratio of 30-70. The profile section takes up, roughly, 30% of the page when factoring in the padding. 
![image](https://github.com/nss-evening-cohort-24/gitsub-team-3/assets/97858910/0422361c-c38b-417e-b81e-4190ab0aa261)

# Dependecies
This issue is dependent on the following for full completion: #4 , #12 , #11. Each content loop will have its own CSS requirements.  

# Dev Notes#
> *STYLE NOTES*
``` 
Font-Family: apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans', Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji
``` 
```
Colors Used: 
Submission buttons on the forms: #218741 (We can use 'Success' in Bootstrap, it's pretty similar tbh).
Font color, in dark mode: #6c6e72.
The heart in sponser on the profile: #994e77
The footer + repose in dark mode font color: #569ff2
Color of heart-rate lines to show repo activity: #42614d
```
```
MISC: _Firefox Snooping_ 
```
![image](https://github.com/nss-evening-cohort-24/gitsub-team-3/assets/97858910/6aba5c8e-663e-4f3d-b1ac-1ca9dd4d4630)
![image](https://github.com/nss-evening-cohort-24/gitsub-team-3/assets/97858910/e55083c1-4d7a-45b6-ae4e-07db657c5438)

**Comment by keanacobarde** [comment]
Updated initial comment.

**Comment by keanacobarde** [comment]
Performed all needed styling changes. Closing ticket.
