### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by GregM1992** [nss-evening-cohort-24/gitsub-team-3#19]
# User Story
The user should see a full and updated README.md on the Github repository page to include screenshots, contributor information, an ideal user breakdown and a loom video showcase.

# Dependecies
A fully functioning site should be completed before every section of the README.md can be filled

# Dev Notes
- Overview Page
- Projects Page
- Package Page
- Repository Page

**Comment by keanacobarde** [comment]
Readme updated and site deployed. Closing ticket.
