### ISSUE TITLE
Make render function

### ISSUE THREAD

**Issue by GregM1992** [nss-evening-cohort-24/gitsub-team-3#3]
# User Story
The user will see the effects of this function, but they will not see the function itself. They will see the cards and HTML components rendered by this function. 

# Acceptance Criteria
WHEN the user launches the page, they will see rendered cards, rendered HTML components such as a Navbar and the profile. This function is responsible for rendering everything the user can see, unless hardcoded directly into the HTML. 

# Dependecies
This issue is not dependent on any other issues for completion, but the issues that are dependent on this issue follows: #5 , #6 , #7. 

# Dev Notes
The renderToDom function is typically written as follows and is regarded as a utility function: 
```
const renderToDom = (divId, html) => { 
document.querySelector(divId).innerHTML = html; 
}
```

**Comment by keanacobarde** [comment]
Edited issue.
