### ISSUE TITLE
Nav bar

### ISSUE THREAD

**Issue by GregM1992** [nss-evening-cohort-24/gitsub-team-3#4]
# User Story
The user will see a consistent navbar, which is consistently styled from page to page. This navbar will include the following elements that are clickable and will render a different layout when clicked: 
- 'Overview', 
- 'Repositories (With a number connected to the number of repos)', 
- 'Projects'
- 'Packages' 

# Acceptance Criteria
WHEN the user launches the page, they will see the navbar as detailed in the user story. 

# Dependecies

While there are not any dependencies, we will need to get the structure of the page and the skeleton of the styling taken care of first before we can start creating the navbar. 

# Dev Notes
The navbar may be contained within the semantic HTML:
```
<nav></nav> 
```
and each component listed as an unordered list item:
```
<ul>. 
```
The styling will be the most difficult part - ensuring that everything is spaced properly in respect to each other but also in respect to other elements on the page.

**Comment by keanacobarde** [comment]
Updated issue.
