### ISSUE TITLE
Loop for package page

### ISSUE THREAD

**Issue by GregM1992** [nss-evening-cohort-24/gitsub-team-3#6]
# User Story
The user, when they click on the 'Packages' item within the navbar should see the following: six evenly spaced cards that have a short description of each package as well as a 'Learn More' button. 
- Title with Icon 
- Description
- Learn More Button

# Acceptance Criteria
Individual cards should follow the format below: 
![image](https://github.com/nss-evening-cohort-24/gitsub-team-3/assets/97858910/db792880-68d8-4b7a-b717-9ce575080e6e)

# Dependecies
#3 - The cards created from the array of data associated with the packages will need to be rendered to the DOM. This function is responsible for that and is necessary before this objective can be completed. As detailed in other issues pertaining to loops, we will need to style the individual cards first before implementing the loop. This may need to be its own seperate issue. 
#16 - Data needs to be created first, housed within an array, in which this array becomes the 

# Dev Notes
- A .forEach() will need to exist for the repo, data array.
- Sample data will need to be created.
- The biggest hurdle will be card styling. A singular card needs to be styled to mirror the objective appearance.

**Comment by keanacobarde** [comment]
Closing issue. Branch was successfully merged. Author marked as 'Done' on project board.
