### ISSUE TITLE
Loop for project page

### ISSUE THREAD

**Issue by GregM1992** [nss-evening-cohort-24/gitsub-team-3#7]
# User Story
The user when clicking on the "project" link in the navbar  should see the projects rendered out properly in the container above the project form.
the container should have a header that shows how many projects are open and closed and a sort button
the body of the container will render a truncated version of the projects 
it will have the 
-name
-last updated stamp
-description
![image](https://github.com/nss-evening-cohort-24/gitsub-team-3/assets/124316602/9e7da7b3-f2a0-4d67-890b-9d3ec2c6448c)
it will also have ellipses on the right side as an option button
![image](https://github.com/nss-evening-cohort-24/gitsub-team-3/assets/124316602/4a803fa9-66d1-4d49-bbd6-fb12e07906cb)

# Acceptance Criteria
if it doesnt look like this 
![image](https://github.com/nss-evening-cohort-24/gitsub-team-3/assets/124316602/43137e20-335a-48d6-b28d-1fe327fc07d7)
its not accepted

# Dependencies
this is reliant on #16 being finished to render from

**Comment by GregM1992** [comment]
issue updated

**Comment by keanacobarde** [comment]
All project JS functionality and styling has been implemented. Closing ticket.
