### ISSUE TITLE
Form for project

### ISSUE THREAD

**Issue by GregM1992** [nss-evening-cohort-24/gitsub-team-3#8]
# User Story
When the user clicks on the "create new project button
a modal should pop up giving them 3 different styles of projects and 2 different templates 
when ever the user clicks on an option a demo image of that style or template is displayed in the container next  to the options.
after choosing a style or template the user may add a name and press the "create" button
then the  modal should close and the new project should render in the appropriate container.

# Acceptance Criteria
when the user clicks "create" a modal should pop up
![image](https://github.com/nss-evening-cohort-24/gitsub-team-3/assets/124316602/0eedb776-5e1a-47f2-ad21-b2be2f0e0898)
when the user clicks an option a demo should be shown to the user
![image](https://github.com/nss-evening-cohort-24/gitsub-team-3/assets/124316602/0a43d48f-572c-47a0-bc01-b4be992ddfb7)
the name input should use the users name and add     "  's untitled project " to it as a placeholder
![image](https://github.com/nss-evening-cohort-24/gitsub-team-3/assets/124316602/7d6081bd-3d17-4ae4-b41f-bea0672c4c02)
the options should consist of:
table
board 
roadmap
team backlog
and feature
![image](https://github.com/nss-evening-cohort-24/gitsub-team-3/assets/124316602/caa2cebb-33ea-4198-99ae-1c7b821d5cc2)

# Dependecies
this is reliant upon the project data array being completed #16

**Comment by GregM1992** [comment]
updated issue

**Comment by keanacobarde** [comment]
Closing issue. Branch was successfully merged. Author marked as 'Done' on project board.

**Comment by keanacobarde** [comment]
All project JS functionality and styling has been implemented. Closing ticket.
